Checklist done
cforlando/energy-saving-trees-ios pull request #74
Opened 2016-10-21 23:29 UTC by PedroTrujilloV

I can’t test the confirmation view controller because is showing for me the address error. I created a pdf version of the image, for the alert controller.

2016-10-30 20:03 UTC, LondonAtlas requested changes
Looking good. Some changes required.

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +            textLabel = (address?.streetAddress)!  + " " +  (address?.secondaryAddress)! ?? "Error retrieving address"
Never use !. It can cause all kinds of problems.

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +            textLabel = (address?.streetAddress)!  + " " +  (address?.secondaryAddress)! ?? "Error retrieving address"
Forcing unwraps will causes crashes and make the ?? useless.

Properties don't require () around them when you are string to concatenate them into a string.
address?.streetAddress!  + " " +  address?.secondaryAddress!
or
"\(address?.streetAddress!)  \(address?.secondaryAddress!)"

Better yet:
let address = address?.streetAddress ?? "No address specified"
let address2 = address?.secondaryAddress ?? "" // 2nd address not required so convert nil to an empty string.
textLabel = "\(address) \(address2)"

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +        if confrim()
always use self when calling a function in the current class.

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    func confrim() -> Bool
type-o

"confirm"

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    func confrim() -> Bool
Also what are we confirming?

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    func item(forRow aRow: Int, inSection aSection: Int) -> STConfirmationDetailRows {
Pass an NSIndexPath

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    func sectionHeader() -> String?
String doesn't need to be an optional since all cases are accounted for.

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    case email
Inconsistent naming.

"Email"

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +import StreetTreesTransportKit
Alpha order the imports

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    var address: STTKStreetAddress?
alpha order variables

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    // MARK: - Table View Methods:
Use the sectioning comments that can be found in the other files.

2016-10-30 20:03 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int
Alpha order functions

2016-10-30 20:12 UTC, LondonAtlas commented
App crashes immediately when trying to move to the Confirm view controller.

2016-10-30 20:22 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +        return dataSource.sections
Always use self when referencing class properties.

2016-10-30 20:23 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +        cell.imageView?.image = imageView
imageView is only ever added once. Move this cell.imageView?.image to the .TreeName case.

2016-10-30 20:27 UTC, LondonAtlas commented
UI is not correct
<img width="487" alt="screen shot 2016-10-30 at 4 25 17 pm" src="https://cloud.githubusercontent.com/assets/1647012/19839729/8f291b06-9ebd-11e6-8e4c-c4c8a62efc41.png">

Please match this:
<img width="333" alt="screen shot 2016-10-30 at 4 26 47 pm" src="https://cloud.githubusercontent.com/assets/1647012/19839742/c54be826-9ebd-11e6-9049-b6be46a662b7.png">

2016-11-01 15:31 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +import StreetTreesTransportKit
Done

2016-11-01 15:32 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    case email
Done

2016-11-01 15:34 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    func sectionHeader() -> String?
Done

2016-11-01 15:42 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    func item(forRow aRow: Int, inSection aSection: Int) -> STConfirmationDetailRows {
Done

2016-11-01 15:43 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    var address: STTKStreetAddress?
Done

2016-11-01 15:46 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    // MARK: - Table View Methods:
Done

2016-11-01 15:59 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +            textLabel = (address?.streetAddress)!  + " " +  (address?.secondaryAddress)! ?? "Error retrieving address"
Done

2016-11-01 16:01 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +        if confrim()
Done

2016-11-01 16:05 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    func confrim() -> Bool
To guard a the variables is better than force an unwrap, like you told me.

2016-11-01 16:13 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +        return dataSource.sections
Done

2016-11-01 16:16 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +        return dataSource.sections
Done

2016-11-01 16:18 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +        cell.imageView?.image = imageView
Done

2016-11-01 16:20 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +    func confrim() -> Bool
Done

2016-11-01 19:28 UTC, LondonAtlas requested changes

2016-11-01 19:28 UTC, LondonAtlas commented on Street Trees/OrderForm.storyboard
> +<<<<<<< HEAD
Conflict city.

2016-11-01 22:29 UTC, akozlik commented on Street Trees/OrderForm.storyboard
> +<<<<<<< HEAD
Great catch.

2016-11-03 18:13 UTC, PedroTrujilloV commented on Street Trees/OrderForm.storyboard
> +<<<<<<< HEAD
Done

2016-11-03 18:13 UTC, PedroTrujilloV commented
UI Done.

2016-11-03 18:13 UTC, closed without merging