Changes done with UI and Bug solved.
cforlando/energy-saving-trees-ios pull request #77
Opened 2016-11-04 01:37 UTC by PedroTrujilloV

Bug Snapshot “What is happening is you have managed to go back to the first view controller right as the location service was updating the user's location and taking a new snapshot. As the snapshot finished rendering the viewcontroller was being deallocated and so the return block was losing a reference to self. This is an excellent bug discovery! Thank you for finding it!”: Tom
- Solved by Tom.
- Tested UI for alert controller.

2016-11-10 16:41 UTC, LondonAtlas requested changes
This is coming together very well! :D

2016-11-10 16:41 UTC, LondonAtlas commented on Street Trees.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 2.3;
this needs to be changed back to 2.2

2016-11-10 16:41 UTC, LondonAtlas commented on Street Trees.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 2.3;
this needs to be changed back to 2.2

2016-11-10 16:41 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +            let sentImage = UIImage(named: "sent")!.imageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal)
Never force unwrap anything other than IBOutlets.

2016-11-10 16:41 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +            alertConfimationMessage.view.addSubview(imageView)
The image and all of this custom framing doesn't look good on the alert. If you want to use the confirmation image, I would create a new view controller and push that on, or remove the image all together.

Second reason to not use an image in an alert view is that you will need to create custom logic for every screen size as it varies from 4S to iPad Pro.

2016-11-10 16:41 UTC, LondonAtlas commented on Street Trees/STConfirmationPageViewController.swift
> +            let okAction = UIAlertAction(title: "Ok", style: .Default, handler: nil)
The OK action to dismiss the order form back to the map view.

2016-11-10 21:28 UTC, PedroTrujilloV commented on Street Trees.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 2.3;
Done

2016-11-10 21:34 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +            let sentImage = UIImage(named: "sent")!.imageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal)
Done

2016-11-14 18:26 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +            let okAction = UIAlertAction(title: "Ok", style: .Default, handler: nil)
Done

2016-11-14 18:26 UTC, PedroTrujilloV commented on Street Trees/STConfirmationPageViewController.swift
> +            alertConfimationMessage.view.addSubview(imageView)
Done.

2016-11-14 18:27 UTC, closed without merging