[App] Swift 3.0 #63
cforlando/energy-saving-trees-ios pull request #89
Opened 2017-04-02 20:33 UTC by markfilter

The FBAnnotationClusterView initializers need to be edited. 2 errors remain.

2017-04-04 23:42 UTC, LondonAtlas requested changes
Looking really good! Some minor changes are required before we can merge into master though.

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesTransportKit/STTKWufooRequest.swift
> +        self.httpBody = form.data as Data?
as Data? isn't required since form.data has already beed converted to Data?

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesTransportKit/STTKWufooRequest.swift
> +        guard let apiKey = STTKAPIKey.data(using: String.Encoding.utf8)?.base64EncodedString(options: []) else {
data(using: .utf8) should be sufficient.

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesTransportKit/STTKWufooRequest.swift
> +        let URL = Foundation.URL(string: URLPath)!
"Foundation" isn't required.

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesTransportKit/STTKWufooForm.swift
> +        return self.query.data(using: String.Encoding.utf8)
Remove "String.Encoding"

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesPersistentKit/STPKTreeDescription.swift
> +        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: self.entityName())
NSFetchRequestResult should be changed to the expected managed object class. I.E. STPKTreeDescription

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesPersistentKit/STPKTree.swift
> +        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: self.entityName())
NSFetchRequestResult should be changed to the expected managed object class. I.E. STPKTree

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesPersistentKit/STPKTree.swift
> +        fetchRequest.predicate = NSPredicate(format: "SELF.order == %@", NSNumber(value: anOrderNumber as Int))
should just be able to use anOrderNumber and not have to convert it to an NSNumber

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesPersistentKit/STPKManageObject.swift
> +        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: self.entityName())
NSFetchRequestResult should be changed to the expected managed object class. I.E. STPKManagedObject

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesPersistentKit/STPKCityBounds.swift
> +        let notOutDated = Date().timeIntervalSince(timestamp as Date) < STPKRefetchDuration
city bounds's date object should already be Date

2017-04-04 23:42 UTC, LondonAtlas commented on StreetTreesFoundationKit/STFKLocationRequest.swift
> +        self.handler(nil, error as NSError?)
Please change so that it is possible to return Error?

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STTreeMapViewController.swift
> +        let dateComponents = (Calendar.autoupdatingCurrent as NSCalendar).components([.month, .day], from: Date())
Pretty sure this was the converter but no need to convert to NSCalendar.

Calendar.autoupdatingCurrent.dateComponents([.day, .month], from: Date())

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STTreeDetailsTableViewController.swift
> +                let dateString = DateFormatter.localizedStringFromDate(date, dateStyle: .MediumStyle, timeStyle: .NoStyle)
I think .MediumStyle and .NoStyle should be throwing compile errors

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STTreeMapViewController.swift
> +    lazy var fetchedResultsController: NSFetchedResultsController = { () -> <<error type>> in
This is probably causing a build error "<<error type>>". Remove () -> <<error type>> in as it is not required.

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STAddressFormViewController.swift
> +        } as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as!
Gotta love that converter. Double check the block input variables as this forced cast will probably cause a runtime crash.

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STBaseOrderFormViewController.swift
> +        UIView.animate(withDuration: 0.25, delay: 0.0, options: UIViewAnimationOptions(), animations: { [weak self] in
any particular reason why .CurveEaseInOut was removed?

2017-04-04 23:42 UTC, LondonAtlas commented on Street Trees/STPKCoreData.swift
> +                    newTree.savings = NSDecimalNumber(value: treeData.savings as Double)
This should already be a double in the struct

2017-04-20 00:47 UTC, markfilter commented on StreetTreesFoundationKit/STFKLocationRequest.swift
> +        self.handler(nil, error as NSError?)
The handler method calls specifically for an optional CLLocation and optional NSError objects.  Passing in a Swift Error object only causes a syntax error.  Casting it as an NSError clears the syntax error.

2017-04-20 00:50 UTC, markfilter commented on Street Trees/STTreeMapViewController.swift
> +    lazy var fetchedResultsController: NSFetchedResultsController = { () -> <<error type>> in
That fixed it, but now I see that FBAnnotationClusteringSwift module is not recognized.

2017-04-20 00:54 UTC, markfilter commented on Street Trees/STAddressFormViewController.swift
> +        } as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as!
Yes, do to the scope of the project, I was hoping to get it to compile and then chase down runtime errors.

2017-04-20 00:57 UTC, markfilter commented on Street Trees/STBaseOrderFormViewController.swift
> +        UIView.animate(withDuration: 0.25, delay: 0.0, options: UIViewAnimationOptions(), animations: { [weak self] in
Whoa! Missed that.  Fixed now. Good catch.

2017-04-20 00:59 UTC, markfilter commented on Street Trees/STAddressFormViewController.swift
> +        } as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as! CLGeocodeCompletionHandler as!
...but it is so inelegant and non-Swifty!

2017-06-29 01:06 UTC, merged